---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: kyverno
  namespace: flux-system
spec:
  interval: 1m0s
  ref:
    semver: '>1.0.0'
  url: https://github.com/kyverno/kyverno
